---
# Einloggen in das Test Hitachi Array, token erstellen
- name : Einloggen am Array
  hosts: e900
  tasks:
  - name: 'Auth & get token'
    uri:
      url: 'http://{{ address }}/ConfigurationManager/v1/objects/sessions'
      method: POST
      body:
        {"authenticationTimeout":600}
      body_format: json
      headers:
        Authorization: "Basic {{ (username + ':' + password) | string | b64encode }}"
        Content-Type: 'application/json'
      validate_certs: no
    register: SessionToken

#zeige (nur) den Token an
  - name: Token Anzeigen
    debug:
      var: SessionToken["json"]["token"]

# lese alle ldev aus
  - name: 'get ldev'
    uri:
      url: 'http://{{ address }}/ConfigurationManager/simple/v1/objects/volumes?startVolumeId=0&capacityUnit=block'
      method: GET
      headers:
        Connection: 'keep-alive'
        Accept: 'application/json, text/plain, */*'
        X-Agent-Request-Id: 'SessionToken["json"]["token"]'
        X-Agent-Type: 'SAE UI/{{ address }}'
        Authorization: 'Session SessionToken["json"]["token"]'
        Content-Type: 'application/json'
        Referer: 'http://{{ address }}/StorageAdvisorEmbedded/'
      validate_certs: no
    register: ldevs

# zeige alle ldev als json an   
  - name: Token Anzeigen
    debug:
      var: ldevs